{"uuid":"24632da3-0b9e-42be-af2b-d6814516beda","historyId":"422e4f5b541660feea4ea418ce6f566a","fullName":"com.thetestingacademy.ex_06_TestAssetions.APITesting026_TestNG_Assertions.test_softAssertEX","labels":[{"name":"package","value":"com.thetestingacademy.ex_06_TestAssetions.APITesting026_TestNG_Assertions"},{"name":"testClass","value":"com.thetestingacademy.ex_06_TestAssetions.APITesting026_TestNG_Assertions"},{"name":"testMethod","value":"test_softAssertEX"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"ATB11xAPIAutomationPrograms"},{"name":"subSuite","value":"com.thetestingacademy.ex_06_TestAssetions.APITesting026_TestNG_Assertions"},{"name":"host","value":"Shyams-Air"},{"name":"thread","value":"49123@Shyams-Air.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"test_softAssertEX","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"The following asserts failed:\n\texpected [Shyam] but found [shyam]","trace":"java.lang.AssertionError: The following asserts failed:\n\texpected [Shyam] but found [shyam]\n\tat org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)\n\tat org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)\n\tat com.thetestingacademy.ex_06_TestAssetions.APITesting026_TestNG_Assertions.test_softAssertEX(APITesting026_TestNG_Assertions.java:29)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:741)\n\tat org.testng.TestRunner.run(TestRunner.java:616)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\n\tat org.testng.TestNG.run(TestNG.java:1079)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1746892994781,"stop":1746892994787}